name:                bitcoin-dca
version:             0.2.0.1
github:              "tochicool/bitcoin-dca"
license:             BSD3
author:              "Tochi Obudulu"
maintainer:          "tochicool@gmail.com"
copyright:           "2020-2022 Tochi Obudulu"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Automate dollar cost averaging on exchanges
category:            Finance, Web

description:         Please see the README on GitHub at <https://github.com/tochicool/bitcoin-dca#readme>

dependencies:
- aeson
- async
- base >= 4.7 && < 5
- base64
- bitcoin-scripting
- bytestring
- co-log
- containers
- cron
- cryptonite
- forkable-monad
- haskoin-core
- http-client
- http-client-tls
- http-types
- memory
- monad-validate
- mtl
- optparse-applicative
- pretty-simple
- retry
- safe-money
- semver
- servant
- servant-client
- stm
  - stm-delay
- text
- time
- unliftio
- unordered-containers
- uuid
- yaml

ghc-options:
  - -Wall -Wno-name-shadowing

library:
  source-dirs: src

executables:
  bitcoin-dca:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    when:        
    - condition: false
      other-modules: Paths_bitcoin_dca
    dependencies:
    - bitcoin-dca

tests:
  bitcoin-dca-test:
    main: "Driver.hs"
    source-dirs: "test"
    dependencies:
    - base
    - bitcoin-dca
    - generic-random
    - QuickCheck
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-smallcheck
    build-tools:
      tasty-discover:tasty-discover
