apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bitcoin-dca

resources:
- ../base
- https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.18.1/controller.yaml
- config-sealed-secret.yaml

configurations:
- sealed-secret-config.yaml

generatorOptions:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    sealedsecrets.bitnami.com/namespace-wide: "true"

secretGenerator:
- name: config
  type: Opaque
