apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bitcoin-dca

resources:
- namespace.yaml
- deployment.yaml

images:
  - name: bitcoin-dca
    newName: ghcr.io/tochicool/bitcoin-dca
    newTag: latest
